### ISSUE TITLE
Github Oauth example

### ISSUE THREAD

**Issue by Djiit** [JaneJeon/blink#726]
Hey, any example on using a github oauth app ? Keycloak link in the doc is not really helping (I'm not sure where to put client id and secrets in Blink doc).

Thanks

**Comment by JaneJeon** [comment]
So while OIDC is built _on top of_ OAuth, it is _not_ OAuth, so you'll need an OIDC provider to start with (the difference being, OAuth is actually an _authorization_ protocol, not an _authentication_ protocol!)

As for where to put the credentials, it is listed here: https://docs.blink.rest/Installation/2.1%20Prerequisites#client (note that it doesn't need the secret due to using OIDC public authentication). You can use something like https://github.com/dexidp/dex to broker GitHub's OAuth into an OIDC, or just use an actual OIDC provider like keycloak/auth0/[authelia](https://www.authelia.com/docs/configuration/identity-providers/oidc.html)/authentik/etc.

If you have any questions, please ask, but for now I'll be closing this as Blink is not meant to work with OAuth2.
