### ISSUE TITLE
Request for a docker compose without needing to build

### ISSUE THREAD

**Issue by HrBingR** [JaneJeon/blink#749]
Currently the compose.yml file builds the image from source, despite images being available.

It would make it more user-friendly to have a docker-compose.yml that shows how to compose an instance using a pre-built image, rather than having to piece it together from the compose.yml and the docker run instructions on the blink docs.

**Comment by JaneJeon** [comment]
Hi, the docker-compose is literally _just_ for development. You _shouldn't_ be using the docker-compose.yml at the top-level of this repo for _deployment_(!) (maybe I should've been more clear on this)

What we could do, instead, is to add a _separate_ (because again, the top-level one is meant for local development) docker-compose.yml file, somewhere else in the repository (e.g. `deploy/docker-compose/compose.yml`).

Given that, as you've said, the image _is_ already available, it should be really easy to get a minimal setup going (the only dependencies are postgres and redis). Once you do have such a compose file, would you mind creating a PR with it? I'd be glad to accept it into the repo!

**Comment by HrBingR** [comment]
Pull request submitted!

#750

**Comment by JaneJeon** [comment]
Left one comment, but otherwise looks good!

**Comment by JaneJeon** [comment]
@HrBingR https://docs.blink.rest/Installation/2.2%20Shortcut#docker-compose-deployment ;)

Thanks for the contribution!
